# @package _global_
dataset:
  _name_: dechat_simhigh
  samplesID: 
    long:
      - ontR10
  true_abund: /home/work/wenhai/simulate_genome_data/PanTax/prepare/1000strains/true_species_abundance.txt
  strain_true_abund: /home/work/wenhai/simulate_genome_data/PanTax/prepare/1000strains/distribution.txt
  reads_path:
    ontR10:
      ontR10_reads_fq: /home/work/yichen/work/Error_correction/ALL-test/1000x-meta/ont/result/10.19dechat-null/reads.ec.fa
      ontR10_reads_fa: 
      ontR10_read_length: /home/work/wenhai/metaprofiling/bacteria_refgenome_NCBIdata/long_alternative_methods/read_length/sim_1000_ontR104_corrected_read_length.txt
      camisim_reads_mapping_path: /home/work/wenhai/simulate_genome_data/PanTax/long_read/new_1000strains/sim-1000strains-ge1-ontR104raw/2024.02.04_16.11.39_sample_0/reads/reads_mapping.tsv.gz
