# @package _global_
dataset:
  _name_: simhigh-sub0.01
  samplesID: 
    short:
      - ngs
    long:
      - hifi
      - ontR9
      - ontR10
      - clr
  true_abund: /home/work/wenhai/simulate_genome_data/PanTax/prepare/1000strains/true_species_abundance.txt
  strain_true_abund: /home/work/wenhai/simulate_genome_data/PanTax/prepare/1000strains/distribution.txt
  reads_path:
    ngs:
      ngs_reads_fq: /home/work/wenhai/simulate_genome_data/PanTax_mutation/simhigh/ngs/mut_rate0.01/simhigh-ngs-mut_rate0.01.fq.gz
      ngs_reads_fq1: /home/work/wenhai/simulate_genome_data/PanTax_mutation/simhigh/ngs/mut_rate0.01/read1.fq
      ngs_reads_fq2: /home/work/wenhai/simulate_genome_data/PanTax_mutation/simhigh/ngs/mut_rate0.01/read2.fq
      ngs_read_length: 150
      camisim_reads_mapping_path: 
      pantax_db:
    hifi:
      hifi_reads_fq: /home/work/wenhai/simulate_genome_data/PanTax_mutation/simhigh/hifi/mut_rate0.01/simhigh-hifi-mut_rate0.01.fq.gz
      hifi_reads_fa:
      hifi_read_length: 
      camisim_reads_mapping_path: 
      pantax_db:
    ontR9:
      ontR9_reads_fq: /home/work/wenhai/simulate_genome_data/PanTax_mutation/simhigh/ontR9/mut_rate0.01/simhigh-ontR9-mut_rate0.01.fq.gz
      ontR9_reads_fa: 
      ontR9_read_length: 
      camisim_reads_mapping_path: 
      pantax_db:
    ontR10:
      ontR10_reads_fq: /home/work/wenhai/simulate_genome_data/PanTax_mutation/simhigh/ontR10/mut_rate0.01/simhigh-ontR10-mut_rate0.01.fq.gz
      ontR10_reads_fa:
      ontR10_read_length: 
      camisim_reads_mapping_path: 
      pantax_db:
    clr:
      clr_reads_fq: /home/work/wenhai/simulate_genome_data/PanTax_mutation/simhigh/clr/mut_rate0.01/simhigh-clr-mut_rate0.01.fq.gz
      clr_reads_fa:
      clr_read_length: 
      camisim_reads_mapping_path: 
      pantax_db: