# @package _global_
dataset:
  _name_: simhigh-gtdb
  samplesID: 
    short:
      - ngs
    long:
      - hifi
      - ontR9
      - ontR10
      - clr
  true_abund: /home/work/wenhai/simulate_genome_data/PanTax/prepare/30_species/true_species_abundance.txt
  strain_true_abund: /home/work/wenhai/simulate_genome_data/PanTax_GTDB_1w/prepare/simhigh/distribution.txt
  # ncbi_taxid2gtdb_taxid: /home/work/wenhai/simulate_genome_data/PanTax_GTDB_1w/prepare/simlow/sim_genomes_info.txt
  reads_path:
    ngs:
      ngs_reads_fq: /home/work/wenhai/simulate_genome_data/PanTax_GTDB_1w/simhigh/ngs/simhigh_ngs/2025.02.16_00.31.54_sample_0/reads/anonymous_reads.fq.gz
      ngs_reads_fq1: /home/work/wenhai/simulate_genome_data/PanTax_GTDB_1w/simhigh/ngs/simhigh_ngs/2025.02.16_00.31.54_sample_0/reads/read1.fq
      ngs_reads_fq2: /home/work/wenhai/simulate_genome_data/PanTax_GTDB_1w/simhigh/ngs/simhigh_ngs/2025.02.16_00.31.54_sample_0/reads/read2.fq
      ngs_read_length: 150
      camisim_reads_mapping_path: 
      pantax_db:
    hifi:
      hifi_reads_fq: /home/work/wenhai/simulate_genome_data/PanTax_GTDB_1w/simhigh/hifi/simhigh_hifi/2025.02.16_00.28.44_sample_0/reads/anonymous_reads.fq.gz
      hifi_reads_fa:
      hifi_read_length: 
      camisim_reads_mapping_path: 
      pantax_db:
    ontR9:
      ontR9_reads_fq: /home/work/wenhai/simulate_genome_data/PanTax_GTDB_1w/simhigh/ontR941/simhigh_ontR941/2025.02.16_11.08.49_sample_0/reads/anonymous_reads.fq.gz
      ontR9_reads_fa: 
      ontR9_read_length: 
      camisim_reads_mapping_path: 
      pantax_db:
    ontR10:
      ontR10_reads_fq: /home/work/wenhai/simulate_genome_data/PanTax_GTDB_1w/simhigh/ontR104/simhigh_ontR104/2025.02.17_22.29.53_sample_0/reads/anonymous_reads.fq.gz
      ontR10_reads_fa:
      ontR10_read_length: 
      camisim_reads_mapping_path: 
      pantax_db:
    clr:
      clr_reads_fq: /home/work/wenhai/simulate_genome_data/PanTax_GTDB_1w/simhigh/clr/simhigh_clr/2025.02.17_22.46.59_sample_0/reads/anonymous_reads.fq.gz
      clr_reads_fa:
      clr_read_length: 
      camisim_reads_mapping_path: 
      pantax_db:
