# @package _global_
dataset:
  _name_: simlow
  samplesID: 
    short:
      - ngs
    long:
      - hifi
      - ontR9
      - ontR10
      - clr
  true_abund: /home/work/wenhai/simulate_genome_data/PanTax/prepare/30_species/true_species_abundance.txt
  strain_true_abund: /home/work/wenhai/simulate_genome_data/PanTax/short_read/30_species/sim-30species-ngs/distributions/distribution_0.txt
  reads_path:
    ngs:
      ngs_reads_fq: 
      ngs_reads_fq1: 
      ngs_reads_fq2: 
      ngs_read_length: 150
      camisim_reads_mapping_path: 
      pantax_db:
    hifi:
      hifi_reads_fq: 
      hifi_reads_fa:
      hifi_read_length: 
      camisim_reads_mapping_path: 
      pantax_db:
    ontR9:
      ontR9_reads_fq: 
      ontR9_reads_fa: 
      ontR9_read_length: 
      camisim_reads_mapping_path:
      pantax_db: 
    ontR10:
      ontR10_reads_fq: 
      ontR10_reads_fa:
      ontR10_read_length: 
      camisim_reads_mapping_path: 
      pantax_db:
    clr:
      clr_reads_fq: 
      clr_reads_fa:
      clr_read_length: 
      camisim_reads_mapping_path: 
      pantax_db: