# @package _global_
dataset:
  _name_: spiked_in_eight_species666_large_pangenome
  samplesID: 
    short:
      - ngs
    long:
      - hifi
      - ontR9
      - ontR10
      - clr
  true_abund: 
  strain_true_abund: /home/work/wenhai/simulate_genome_data/PanTax_species_666_for_large_pangenome/eight/metadata/distribution.txt
  reads_path:
    ngs:
      ngs_reads_fq: 
      ngs_reads_fq1: /home/work/wenhai/simulate_genome_data/PanTax_species_666_for_large_pangenome/eight/sim_species666_eight_ngs/2024.12.26_16.58.02_sample_0/reads/shuffle_spiked_in_ngs_1.fq
      ngs_reads_fq2: /home/work/wenhai/simulate_genome_data/PanTax_species_666_for_large_pangenome/eight/sim_species666_eight_ngs/2024.12.26_16.58.02_sample_0/reads/shuffle_spiked_in_ngs_2.fq
      ngs_read_length: 150
      camisim_reads_mapping_path: 
      pantax_db: 
    hifi:
      hifi_reads_fq: /home/work/wenhai/simulate_genome_data/PanTax_species_666_for_large_pangenome/eight/sim_species666_eight_hifi/2024.12.26_17.45.32_sample_0/reads/shuffle_spiked_in_hifi.fq
      hifi_reads_fa:
      hifi_read_length: 
      camisim_reads_mapping_path: 
      pantax_db: 
    ontR9:
      ontR9_reads_fq: /home/work/wenhai/simulate_genome_data/PanTax_species_666_for_large_pangenome/eight/sim_species666_eight_ontr9/2024.12.26_18.34.32_sample_0/reads/shuffle_spiked_in_ontr9.fq
      ontR9_reads_fa: 
      ontR9_read_length: 
      camisim_reads_mapping_path: 
      pantax_db:
    ontR10:
      ontR10_reads_fq: /home/work/wenhai/simulate_genome_data/PanTax_species_666_for_large_pangenome/eight/sim_species666_eight_ontr10/2024.12.26_18.40.36_sample_0/reads/shuffle_spiked_in_ontr10.fq
      ontR10_reads_fa:
      ontR10_read_length: 
      camisim_reads_mapping_path: 
      pantax_db:
    clr:
      clr_reads_fq: /home/work/wenhai/simulate_genome_data/PanTax_species_666_for_large_pangenome/eight/sim_species666_eight_clr/2024.12.26_18.11.55_sample_0/reads/shuffle_spiked_in_clr.fq
      clr_reads_fa:
      clr_read_length: 
      camisim_reads_mapping_path: 
      pantax_db: