# @package _global_
tool:
  _name_: ganon
  species_level:
    db: 
  strain_level:
    db: /home/work/wenhai/metaprofiling/bacteria_refgenome_NCBIdata/alternative_methods/ganon/ganon_db
  zymo1_strain_level:
    db: /home/work/wenhai/metaprofiling/bacteria_refgenome_NCBIdata/alternative_methods/ganon/zymo1_strain/ganon_db
    database_genomes_info: /home/work/wenhai/metaprofiling/bacteria_refgenome_NCBIdata/multi_species_single_strain_zymo/genomes_info_sample.txt
  spiked_in_strain_level:
    db: /home/work/wenhai/metaprofiling/bacteria_refgenome_NCBIdata/alternative_methods/ganon/spiked_in_666/ganon_db
    database_genomes_info: /home/work/wenhai/metaprofiling/bacteria_refgenome_NCBIdata/single_species_strain_level_666/pantax/pantax_db/genomes_info.txt
  spiked_in_strain_level_species666_large_pangenome:
    db: /home/work/wenhai/metaprofiling/bacteria_refgenome_NCBIdata/alternative_methods/ganon/ganon_db
    designated_genomes_info: /home/work/wenhai/simulate_genome_data/PanTax_species_666_for_large_pangenome/scripts/genomes_info.txt
  gtdb_strain_level:
    db: /home/work/wenhai/metaprofiling/bacteria_refgenome_NCBIdata/alternative_methods/ganon/gtdb100/ganon_db
    database_genomes_info: /home/work/wenhai/metaprofiling/bacteria_GTDB/data/genomes_info.txt
  # profile level tool can do
  profile_level: 
    - species_level
    - strain_level
    - zymo1_strain_level
    - spiked_in_strain_level
    - spiked_in_strain_level_species666_large_pangenome
    - gtdb_strain_level
  read_type:
    - short
    - long