# @package _global_
tool:
  _name_: hifiasm
  species_level:
    db: 
  strain_level:
    db: /home/work/wenhai/metaprofiling/bacteria_refgenome_NCBIdata/asm2prof/asm2prof_db/res/Ref13404/reference.fna.gz
    reference_len_stat: /home/work/wenhai/metaprofiling/bacteria_refgenome_NCBIdata/asm2prof/asm2prof_db/res/Ref13404/reference_len_stat.txt
  zymo1_strain_level:
    db: 
    database_genomes_info: /home/work/wenhai/metaprofiling/bacteria_refgenome_NCBIdata/multi_species_single_strain_zymo/genomes_info_sample.txt
  spiked_in_strain_level:
    db: 
    database_genomes_info: /home/work/wenhai/metaprofiling/bacteria_refgenome_NCBIdata/single_species_strain_level_666/pantax/pantax_db/genomes_info.txt
  spiked_in_strain_level_species666_large_pangenome:
    db: 
    designated_genomes_info: /home/work/wenhai/simulate_genome_data/PanTax_species_666_for_large_pangenome/scripts/genomes_info.txt
  gtdb_strain_level:
    db: 
    database_genomes_info: /home/work/wenhai/metaprofiling/bacteria_GTDB/data/genomes_info.txt

  # profile level tool can do
  profile_level: 
    - species_level
    - strain_level
    - zymo1_strain_level
    # - spiked_in_strain_level
    # - spiked_in_strain_level_species666_large_pangenome
    # - gtdb_strain_level
  read_type:
    # - short
    - long
  samplesID:
    - hifi
