# @package _global_
tool:
  _name_: instrain
  strain_level:
    db: /home/work/wenhai/metaprofiling/bacteria_refgenome_NCBIdata/alternative_methods/instrain/strain/reference.fna.bt2
    reference_fna: /home/work/wenhai/metaprofiling/bacteria_refgenome_NCBIdata/alternative_methods/instrain/strain/reference.fna
    strain_stb: /home/work/wenhai/metaprofiling/bacteria_refgenome_NCBIdata/alternative_methods/instrain/strain/strain.stb

  # profile level tool can do
  profile_level: 
    - strain_level

  
  read_type:
    - short


