# @package _global_
tool:
  _name_: pantax
  species_level:
    db: /home/work/wenhai/PanTax/pantax_db
  strain_level:
    db: /home/work/wenhai/PanTax/pantax_db
  zymo1_strain_level:
    db: /home/work/wenhai/metaprofiling/bacteria_refgenome_NCBIdata/multi_species_single_strain_zymo/pantax_db
    database_genomes_info: /home/work/wenhai/metaprofiling/bacteria_refgenome_NCBIdata/multi_species_single_strain_zymo/genomes_info_sample.txt
  spiked_in_strain_level:
    db: /home/work/wenhai/metaprofiling/bacteria_refgenome_NCBIdata/single_species_strain_level_666/pantax/pantax_db
    database_genomes_info: /home/work/wenhai/metaprofiling/bacteria_refgenome_NCBIdata/single_species_strain_level_666/pantax/pantax_db/genomes_info.txt
  spiked_in_strain_level_species666_large_pangenome:
    db: /home/work/wenhai/PanTax/pantax_db
    designated_species: 666
  gtdb_strain_level:
    db: "-"
    database_genomes_info: /home/work/wenhai/metaprofiling/bacteria_GTDB/data/genomes_info.txt

  reference_diversity_strain_level:
    db: [
      /home/work/wenhai/metaprofiling/bacteria_refgenome_NCBIdata/reference_diversity/reference/reference_db/ref1/ref1_pantax_db,
      /home/work/wenhai/metaprofiling/bacteria_refgenome_NCBIdata/reference_diversity/reference/reference_db/ref2/ref2_pantax_db,
      /home/work/wenhai/metaprofiling/bacteria_refgenome_NCBIdata/reference_diversity/reference/reference_db/ref3/ref3_pantax_db,
      /home/work/wenhai/metaprofiling/bacteria_refgenome_NCBIdata/reference_diversity/reference/reference_db/ref4/ref4_pantax_db,
      /home/work/wenhai/metaprofiling/bacteria_refgenome_NCBIdata/reference_diversity/reference/reference_db/ref5/ref5_pantax_db
    ]
  reference_diversity_strain_level_ref_num: 0

  zymo1_reference_diversity_strain_level:
    db: [
      "/home/work/wenhai/metaprofiling/bacteria_refgenome_NCBIdata/zymo1_reference_diversity/reference/reference_db/ref1/zymo1_ref1_pantax_db",
      "/home/work/wenhai/metaprofiling/bacteria_refgenome_NCBIdata/zymo1_reference_diversity/reference/reference_db/ref2/zymo1_ref2_pantax_db"
    ]
  zymo1_reference_diversity_strain_level_ref_num: 0

  # profile level tool can do
  profile_level: 
    - species_level
    - strain_level
    - zymo1_strain_level
    - spiked_in_strain_level
    - spiked_in_strain_level_species666_large_pangenome
    - gtdb_strain_level
    - reference_diversity_strain_level
  
  read_type:
    - short
    - long

  mode: all

  extra_strain_profiling_paras:

  version:

  graph_parsing_format:

  is_debug: true

  # sensitivity_analysis
  sensitivity_analysis: false
  sensitivity_analysis_low: false
  more_sensitivity_analysis: false
  rescue_sensitivity_analysis: false
  sensitivity_analysis_wd: ${top_wd}

  graph_mapq: false

  # low coverage eval
  low_cov_eval: false