# @package _global_
tool:
  _name_: sylph
  species_level:
    db: /home/work/wenhai/metaprofiling/bacteria_refgenome_NCBIdata/alternative_methods/sylph/species_database/database.syldb
    seq2tax: /home/work/wenhai/metaprofiling/bacteria_refgenome_NCBIdata/alternative_methods/sylph/species_database/seqid2taxid.map
  strain_level:
    db: /home/work/wenhai/metaprofiling/bacteria_refgenome_NCBIdata/alternative_methods/sylph/strain_database/database.syldb
    seq2tax: /home/work/wenhai/metaprofiling/bacteria_refgenome_NCBIdata/scripts/data/fna_seqID_taxid.txt
  zymo1_strain_level:
    db: /home/work/wenhai/metaprofiling/bacteria_refgenome_NCBIdata/alternative_methods/sylph/zymo1_strain_database/database.syldb
    seq2tax: /home/work/wenhai/metaprofiling/bacteria_refgenome_NCBIdata/scripts/data/zymo1_fna_seqID_taxid.txt
    database_genomes_info: /home/work/wenhai/metaprofiling/bacteria_refgenome_NCBIdata/multi_species_single_strain_zymo/genomes_info_sample.txt
  # profile level tool can do
  profile_level: 
    - species_level
    - strain_level
    - zymo1_strain_level
  
  read_type:
    - short
    - long